### ISSUE TITLE
Refresh/Reload capability

### ISSUE THREAD

**Issue by vyelchuri** [davidebbo/MvcApplicationRazorGeneratorSeparateLibrary#2]
@davidebbo @pranav I am refreshing the browser after changing the file content of `About.cshtml`. Edited text were not rendering until rebuild the project. I used the `UsePhysicalViewsIfNewer` as true

**Comment by vyelchuri** [comment]
Can some one help me out on this issue ? There is any alternates to enable an option Refresh/Reload (Edit the razor template and refresh the browser with out rebuild). Razor templates are supposed to be in separate library like this example.

**Comment by davidebbo** [comment]
Best to use https://github.com/RazorGenerator/RazorGenerator for tracking issues.

**Comment by davidebbo** [comment]
Though I think that `UsePhysicalViewsIfNewer` is not expected to work when using a separate library.
